name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.14
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - plotly
  - biopython
  - flask
  - sqlalchemy
  - requests
  - python-dotenv
  - ipykernel
  - tqdm
  - pip
  - pip:
      - flask-sqlalchemy
      - flask-login


